// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_DpiT2f8dBNR_Lf5hnCTAoFySsPqvkeM',
    appId: '1:915333130723:web:819f326ca4ff9e4867d8d6',
    messagingSenderId: '915333130723',
    projectId: 'placement-7fe1d',
    authDomain: 'placement-7fe1d.firebaseapp.com',
    storageBucket: 'placement-7fe1d.firebasestorage.app',
    measurementId: 'G-KG2YE6FCQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKftf1XEBYNvZ0m9sDZgDsIgqASJ_PiNs',
    appId: '1:915333130723:android:fa8e0ad7801cca2b67d8d6',
    messagingSenderId: '915333130723',
    projectId: 'placement-7fe1d',
    storageBucket: 'placement-7fe1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxaS4xyJ3Tm_Hvor3g3Y6LOoqbejrzJes',
    appId: '1:915333130723:ios:71c5e80979992aba67d8d6',
    messagingSenderId: '915333130723',
    projectId: 'placement-7fe1d',
    storageBucket: 'placement-7fe1d.firebasestorage.app',
    iosBundleId: 'com.example.placement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxaS4xyJ3Tm_Hvor3g3Y6LOoqbejrzJes',
    appId: '1:915333130723:ios:71c5e80979992aba67d8d6',
    messagingSenderId: '915333130723',
    projectId: 'placement-7fe1d',
    storageBucket: 'placement-7fe1d.firebasestorage.app',
    iosBundleId: 'com.example.placement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_DpiT2f8dBNR_Lf5hnCTAoFySsPqvkeM',
    appId: '1:915333130723:web:af460f671224133a67d8d6',
    messagingSenderId: '915333130723',
    projectId: 'placement-7fe1d',
    authDomain: 'placement-7fe1d.firebaseapp.com',
    storageBucket: 'placement-7fe1d.firebasestorage.app',
    measurementId: 'G-DZNW2HL7HD',
  );
}
